### ISSUE TITLE
Why the use of the MSScript object?

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [AigioL/OpenInternetExplorer#1]
With the code you're using to call the MSScript object to execute a piece of VBScript that calls the Internet Explorer object, you could easily call the IE object directly.

**Comment by AigioL** [comment]
https://github.com/AigioL/OpenInternetExplorer/commit/3f7ace06175e82ea167626e1725f7a2ca68bcecf Changed to COMReference MSScriptControl
