### ISSUE TITLE
Files such as ".html" cannot be opened by right-clicking "Open as".

### ISSUE THREAD

**Issue by ghost** [AigioL/OpenInternetExplorer#2]
Bug: Files like ".html" cannot be opened by right-clicking "Open as".
![bug](https://user-images.githubusercontent.com/62967959/180700264-95ada8a1-965b-43c7-865b-50fb8cfdab3c.gif)

**Comment by roco3d** [comment]
If you can modify the windows registry you can follow the instructions showed here: 
[https://stackoverflow.com/questions/11881938/right-click-open-with-arguments](https://stackoverflow.com/questions/11881938/right-click-open-with-arguments)

**Comment by AigioL** [comment]
v1.3 fix this.
