### ISSUE TITLE
use CLI (command line interface)

### ISSUE THREAD

**Issue by WolfZahn** [AigioL/OpenInternetExplorer#5]
Hi, 
it would be a charm to have a CLI.
Like this:
C:\TMP>OpenInternetExplorer.exe 192.168.1.1
to open start the OpenInternetExplorer at that adress.

**Comment by BlackusPL** [comment]
You can do that by this: OpenInternetExplorer.exe "http://192.168.1.1"

**Comment by WolfZahn** [comment]
Ah, I tried without http://
Thanks for the hint.
